# Must register the Posh-ACME account prior to running this script
# Registration script: posh_register_acme.ps1
# Repo: https://github.com/scott0bailey/sectigo/blob/main/posh_register_acme.ps1

# ------------------------------------------------------------
# 1. Gather Inputs
# ------------------------------------------------------------

# Prompt user for the primary certificate domain (Common Name / CN)
$domainName = Read-Host "Enter the Main Domain (CN)"

# Prompt user for optional SAN entries (comma‑separated)
$sanInput = Read-Host "Enter any SAN names (comma-separated, or leave blank)"

# Convert SAN input into an array and merge with the CN
$allDomains = @($domainName)
if ($sanInput) {
    # Split on commas, trim whitespace, and append to the domain list
    $allDomains += $sanInput.Split(',').Trim()
}

# ------------------------------------------------------------
# 2. Silence background noise
# ------------------------------------------------------------

# Suppress PowerShell progress bars for cleaner output
$ProgressPreference = 'SilentlyContinue'

# Suppress informational messages from modules
$InformationPreference = 'SilentlyContinue'

# ------------------------------------------------------------
# Generate a Random PFX Password
# ------------------------------------------------------------

# Length for the auto-generated password
$passwordLength = 16

# Create a random mix of uppercase, lowercase, and numbers
$pfxPassword = -join (
    (65..90) + (97..122) + (48..57) |
    Get-Random -Count $passwordLength |
    ForEach-Object {[char]$_}
)

# ------------------------------------------------------------
# 3. Create the directory .\<CN>\ (silent)
# ------------------------------------------------------------

# Build the output directory path based on the CN
$targetDir = Join-Path -Path (Get-Location) -ChildPath $domainName

# Only create the directory if it doesn't already exist
if (-not (Test-Path $targetDir)) {
    New-Item -Path $targetDir -ItemType Directory | Out-Null
}

# ------------------------------------------------------------
# 4. Request the certificate (silent)
# ------------------------------------------------------------

# New-PACertificate will perform DNS validation via Posh‑ACME's
# plugin settings and generate the cert + PFX files internally
New-PACertificate -Domain $allDomains -AcceptTOS -Install *>$null

# ------------------------------------------------------------
# 5. Retrieve the completed certificate order
# ------------------------------------------------------------

# Fetch the certificate order object for the CN
$certOrder = Get-PACertificate -MainDomain $domainName

# ------------------------------------------------------------
# 6. Build destination path for the exported PFX
# ------------------------------------------------------------

# Save the PFX inside the CN directory using <CN>.pfx
$pfxPath = Join-Path -Path $targetDir -ChildPath "$domainName.pfx"

# ------------------------------------------------------------
# 7. Copy the PFX generated by Posh‑ACME
# ------------------------------------------------------------

# Posh‑ACME creates the PFX automatically; we relocate it for convenience
if (Test-Path $certOrder.PfxFullChain) {
    Copy-Item -Path $certOrder.PfxFullChain -Destination $pfxPath -Force
}

# ------------------------------------------------------------
# 8. Final Output Summary
# ------------------------------------------------------------

Write-Host "`n----------------------------------------------------" -ForegroundColor Cyan
Write-Host "Certificate Request Complete!" -ForegroundColor Green
Write-Host "Directory:    $targetDir"
Write-Host "PFX File:     $domainName.pfx"
Write-Host "PFX Password: $pfxPassword"
Write-Host "----------------------------------------------------" -ForegroundColor Cyan
